service: oscon-photo-booth

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod

custom:
  bucketName: oscon-2017-selfies

functions:
  new:
    handler: handler.newSelfie
    memorySize: 128
    timeout: 30
    environment:
      BUCKET: ${self:custom.bucketName}
    events:
      - http:
          path: selfie/new
          method: post
          cors: true

resources:
  Resources:
    selfiesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
